version: '3.4'
services:
  ser2net:
    container_name: ser2net
    build: .
    image: ser2net
    environment:
      PORT: "20108"
      DEVICE: "/dev/ttyUSB0"
      CONNOPTIONS: "115200n81,local"
    ports:
      - "20108:20108"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"